import type { Metadata } from "next";
import { Roboto_Mono, Yatra_One } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import dynamic from "next/dynamic"
import { TooltipProvider } from "@/components/tooltip";


const robotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
    weight:  ["400", "500", "700"]
})

const yatraOne = Yatra_One({
    variable: "--font-yatra-one",
    subsets: ["latin"],
    weight:  ["400"]
})

const ScrollToTop = dynamic(() =>
  import("@/components/scroll-to-top").then((mod) => mod.ScrollToTop)
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${robotoMono.variable} ${yatraOne.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          <TooltipProvider>

          <div className="flex flex-col min-h-screen">
            <main className="flex-1">
              {children}
            </main>
            <ScrollToTop />
          </div>
          </TooltipProvider>
        </ThemeProvider >
      </body>
    </html>
  );
}
