export const TECH_STACK_MAP: Record<string, string> = {
    JavaScript: "/icons/tech-stack/javascript.svg",
    TypeScript: "/icons/tech-stack/typescript.svg",
    "Next.js": "/icons/tech-stack/nextjs.svg",
    React: "/icons/tech-stack/react.svg",
    "Tailwind CSS": "/icons/tech-stack/tailwindcss.svg",
    Zustand: "/icons/tech-stack/zustand.svg",
    Tanstack: "/icons/tech-stack/tanstack.svg",
    Motion: "/icons/tech-stack/motion.svg",
    Redux: "/icons/tech-stack/redux.svg",
    Expo: "/icons/tech-stack/expo.svg",
    Node: "/icons/tech-stack/nodejs.svg",
    Bun: "/icons/tech-stack/bun.svg",
    Go: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg",
    Python: "/icons/tech-stack/python.svg",
    MongoDB: "/icons/tech-stack/mongodb.svg",
    PostgreSQL: "/icons/tech-stack/postgresql.svg",
    Figma: "/icons/tech-stack/figma.svg",
    Claude: "/icons/tech-stack/claude.svg"
  };